export const GET_USER_STARTED = 'GET_USER_STARTED';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';

export const GET_SALARY_STARTED = 'GET_SALARY_STARTED';
export const GET_SALARY_SUCCESS = 'GET_SALARY_SUCCESS';
export const GET_SALARY_FAILURE = 'GET_SALARY_FAILURE';